name: dado-memory-game
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello world!
          
  deploy-dev:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: 'https://carolineschererr.github.io/dado-memory-game/'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy Dev
        
  deploy-hmg:
      runs-on: ubuntu-latest
      environment: 
        name: hmg
        url: 'https://carolineschererr.github.io/dado-memory-game/'
      needs: deploy-dev
      steps:
        - name: Run a one-line script
          run: echo Deploy Hmg
      
  deploy-prd:
      runs-on: ubuntu-latest
      environment: 
        name: prd
        url: 'https://carolineschererr.github.io/dado-memory-game/'
      needs: deploy-hmg
      steps:
        - name: Run a one-line script
          run: echo Deploy Prd
